### ISSUE TITLE
progressbar not full width of video

### ISSUE THREAD

**Issue by nooisy** [benhatsor/pretty-youtube#1]
First off, I really like what you did. Great work. I was wondering if it was possible to fix the progressbar not being full width? I've taken a quick look at it but I haven't seen an easy fix yet. I'll keep trying though. Thanks in advance :)

**Comment by benhatsor** [comment]
Hmm.. seems like the bug occurs on specific screen resolutions. I'll look into it, thanks! :D

**Comment by benhatsor** [comment]
Now fixed on my end.
